
---
- name: Playbook to install httpd
  hosts: prod
  gather_facts: no
  tasks:


    - name: Install Httpd
      yum:
       name: httpd
       state: absent

    - name: Enable service to start on boot up
      service:
       name: httpd
       state: stopped

    - name: Create firewall rule for apache service
      firewalld:
       service: http
       zone: public
       permanent: yes
       immediate: yes
       state: absent 

...
